service: dontstress

projectDir: ../

frameworkVersion: "2"
configValidationMode: error
variablesResolutionMode: "20210326"

plugins:
  - serverless-iam-roles-per-function
  - serverless-go

custom:
  go:
    baseDir: ..
  tableBillingMode: PAY_PER_REQUEST
  prefix: ${self:service}-${sls:stage}

package:
  excludeDevDependencies: false

provider:
  name: aws
  region: eu-west-1
  profile: dontstress
  lambdaHashingVersion: 20201221
  logRetentionInDays: 7
  # Global lambda runtime config
  timeout: 5
  runtime: go
  memorySize: 128
  architecture: x86_64
  environment:
    # Global env vars for DAO
    ADMINS_TABLE_NAME: !Ref adminsTable
    LABS_TABLE_NAME: !Ref labsTable
    TASKS_TABLE_NAME: !Ref tasksTable
    FILES_TABLE_NAME: !Ref filesTable
    RUNS_TABLE_NAME: !Ref testRunsTable
    WS_ENDPOINT:
      Fn::Join:
        - ''
        - - https://
          - Ref: WebsocketsApi
          - ".execute-api.eu-west-1."
          - Ref: AWS::URLSuffix
          - "/${sls:stage}"
    BUCKET_NAME: !Ref filesBucket
    LD_LIBRARY_PATH: /opt/lib

functions: ${file(deploy/functions.js)}

resources:
  - ${file(deploy/tables.yaml)}
  - ${file(deploy/buckets.yaml)}

layers: ${file(deploy/layers.yaml)}
