service: dontstress

projectDir: ../

frameworkVersion: "2"
configValidationMode: error
variablesResolutionMode: "20210326"

plugins:
  - serverless-iam-roles-per-function
  - serverless-go-plugin

custom:
  tableBillingMode: PAY_PER_REQUEST
  prefix: ${self:service}-${sls:stage}

provider:
  name: aws
  region: eu-west-1
  profile: dontstress
  lambdaHashingVersion: 20201221
  logRetentionInDays: 7
  # Global lambda runtime config
  timeout: 5
  runtime: go1.x
  memorySize: 128
  architecture: x86_64
  environment:
    # Global env vars for DAO
    LABS_TABLE_NAME: !Ref labsTable
    TASKS_TABLE_NAME: !Ref tasksTable
    FILES_TABLE_NAME: !Ref filesTable
    RUNS_TABLE_NAME: !Ref testRunsTable
    BUCKET_NAME: !Ref filesBucket

functions: ${file(./functions.js)}

resources:
  - ${file(tables.yaml)}
  - ${file(buckets.yaml)}
